version: '3.1'

services:
  db:
    image: berkerarslan/db_postgre_instance:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./database/sql/data:/var/lib/postgresql/data
      - ./database/sql/config/log:/var/log/postgresql # This is a bind mount
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
